/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./views/**/*.ejs', './public/**/*.html'],
  theme: {
    extend: {
      colors: {
        error: 'var(--error)',
        'secondary-container': 'var(--secondary-container)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'surface-container-low': 'var(--surface-container-low)',
        'error-container': 'var(--error-container)',
        'on-surface': 'var(--on-surface)',
        'primary-fixed': 'var(--primary-fixed)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'inverse-primary': 'var(--inverse-primary)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        surface: 'var(--surface)',
        'on-tertiary': 'var(--on-tertiary)',
        'primary-container': 'var(--primary-container)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'on-primary-container': 'var(--on-primary-container)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'outline-variant': 'var(--outline-variant)',
        'surface-container-high': 'var(--surface-container-high)',
        primary: 'var(--primary)',
        'surface-dim': 'var(--surface-dim)',
        'tertiary-container': 'var(--tertiary-container)',
        background: 'var(--background)',
        'on-error-container': 'var(--on-error-container)',
        outline: 'var(--outline)',
        'surface-tint': 'var(--surface-tint)',
        'surface-bright': 'var(--surface-bright)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'surface-container': 'var(--surface-container)',
        secondary: 'var(--secondary)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'surface-variant': 'var(--surface-variant)',
        'on-primary': 'var(--on-primary)',
        'on-secondary': 'var(--on-secondary)',
        'on-background': 'var(--on-background)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'inverse-surface': 'var(--inverse-surface)',
        tertiary: 'var(--tertiary)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'on-error': 'var(--on-error)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '16px',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        'container-max': '1280px',
        gutter: '24px',
      },
      fontFamily: {
        'display-xl': ['Outfit'],
        'label-sm': ['IBM Plex Mono'],
        'headline-sm': ['Outfit'],
        'body-lg': ['Inter'],
        'headline-lg': ['Outfit'],
        'body-md': ['Inter'],
        'label-md': ['IBM Plex Mono'],
      },
      fontSize: {
        'display-xl': ['28px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '1.4', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-sm': ['15px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'headline-lg': ['22px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
